# Singular Value Decompostion

* Library

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pylab
import glob
import pandas as pd
import math as math
import os

In [4]:
a = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])

In [5]:
# set numpy printing options
np.set_printoptions(suppress=True)
np.set_printoptions(precision=3)

In [9]:
print("--- FULL ---")
U, s, VT = np.linalg.svd(a, full_matrices=True)

print("U:\n {}".format(U))
print("s:\n {}".format(s))
print("VT:\n {}".format(VT))


--- FULL ---
U:
 [[-0.138  0.024  0.011  0.99  -0.    -0.     0.   ]
 [-0.413  0.071  0.032 -0.059 -0.885  0.192  0.   ]
 [-0.55   0.094  0.043 -0.079  0.424  0.707  0.   ]
 [-0.688  0.118  0.054 -0.099  0.192 -0.681  0.   ]
 [-0.153 -0.591 -0.654 -0.     0.    -0.    -0.447]
 [-0.072 -0.731  0.678  0.    -0.     0.     0.   ]
 [-0.076 -0.296 -0.327 -0.    -0.    -0.     0.894]]
s:
 [ 12.481   9.509   1.346   0.      0.   ]
VT:
 [[-0.562 -0.593 -0.562 -0.09  -0.09 ]
 [ 0.127 -0.029  0.127 -0.695 -0.695]
 [ 0.41  -0.805  0.41   0.091  0.091]
 [-0.707  0.     0.707 -0.     0.   ]
 [-0.     0.    -0.     0.707 -0.707]]
