# Singular Value Decompostion

$$Z= U\sum V^{T}$$

* Library

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pylab
import glob
import pandas as pd
import math as math
import os

## Z matrix that will be decomposed

Example

In [52]:
Z = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])

In [41]:
# set numpy printing options
np.set_printoptions(suppress=True)
np.set_printoptions(precision=5)

# Full SVD (NumPy)

In [60]:
def np_svd(X):
    return np.linalg.svd(X, full_matrices=True, compute_uv=True)

def np_inv_svd(svd_outputs):
    U, s, V = svd_outputs
    return np.dot(U, np.dot(np.diag(s), V))


In [43]:
U, s, VT= np_svd(a)

$$\begin{split}
     \mathbf{s = \sum} 
     & = \left[
     \begin{array}{ccc}
         \lambda^{-1}_{1} & 0 & 0 & 0\\
          0 &  \lambda^{-1}_{2} & 0 & 0\\
          0 & 0 & \lambda^{-1}_{3} & 0 \\
          0 & 0 & 0 & \lambda^{-1}_{k} \\
     \end{array}
     \right]_{N \times M} \\\\
 \end{split}$$

## U, $\sum$ and $V^T$ matrices

In [54]:
print("U:\n {}".format(U))
print("E:\n {}".format(s))
print("VT:\n {}".format(VT))

U:
 [[-1. -0. -0.  0. -0.]
 [ 0. -1. -0.  0. -0.]
 [ 0.  0. -1.  0. -0.]
 [-0. -0. -0. -1. -0.]
 [-0. -0. -0. -0.  1.]]
E:
 [ 12.48101   9.50861   1.34556   0.        0.     ]
VT:
 [[-0.56226 -0.59286 -0.56226 -0.09013 -0.09013]
 [ 0.12664 -0.02877  0.12664 -0.69538 -0.69538]
 [ 0.40967 -0.80479  0.40967  0.09126  0.09126]
 [-0.70711  0.       0.70711 -0.       0.     ]
 [-0.      -0.       0.       0.70711 -0.70711]]


# We want the Z inverse matrix

$$Z^{-1}=V\sum^{-1}U^{T}$$

Actually, Z inverse is a pseudo-inverse or generalized inverse (penrose), because it is an aproximated solution, and we named Z inverse like:
    $$ Z^{+} = V \sum^{+} U^{T}$$


where $\sum^{+}$ is the matriz that contain the sigular values inverse non-zeros in this way: 

$$\begin{split}
     \mathbf{\sum^{+}} 
     & = \left[
     \begin{array}{ccc}
         E & 0 \\
          0 &  0
     \end{array}
     \right]_{N \times M} \\\\
 \end{split}$$

being E the $kxk$ matriz whose the element i-ésimo is $e_{ii}=e^{-1}_{i}$ for $1\le i\le k$

$$\begin{split}
     \mathbf{E} 
     & = \left[
     \begin{array}{ccc}
         \sigma_{1} & 0 & 0 & 0 & 0\\
          0 &  \sigma_{2} & 0 & 0 & 0\\
          0 & 0 & \sigma_{3} & 0 & 0\\
          0 & 0 & 0 & \sigma_{k} & 0 \\
          0 & 0 & 0 & 0 & 0
     \end{array}
     \right]_{N \times M} \\\\
 \end{split}$$

$\sigma=1/\lambda$

$$\sigma_{1} \gt \sigma_{2} \gt \sigma_{3} \dots \gt \sigma_{k}$$

In [45]:
a = np.dot(np.diag(s), VT)

array([[ 7.01756,  7.39949,  7.01756,  1.12496,  1.12496],
       [-1.20418,  0.27357, -1.20418,  6.61206,  6.61206],
       [-0.55123,  1.0829 , -0.55123, -0.12279, -0.12279],
       [ 0.     ,  0.     , -0.     ,  0.     ,  0.     ],
       [-0.     , -0.     , -0.     ,  0.     , -0.     ]])