# Singular Value Decompostion

$$Z= U\sum V^{T}$$

* Library

In [54]:
import numpy as np
import matplotlib.pyplot as plt
import pylab
import glob
import pandas as pd
import math as math
import os

## Z matrix that will be decomposed

Example

In [52]:
Z = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])

In [2]:
# set numpy printing options
np.set_printoptions(suppress=True)
np.set_printoptions(precision=5)

# Full SVD (NumPy)

In [3]:
def np_svd(X):
    return np.linalg.svd(X, full_matrices=True, compute_uv=True)

def np_inv_svd(svd_outputs):
    U, s, V = svd_outputs
    return np.dot(U, np.dot(np.diag(s), V))


In [43]:
U, s, VT= np_svd(a)

$$\begin{split}
     \mathbf{s = \sum} 
     & = \left[
     \begin{array}{ccc}
         \lambda^{-1}_{1} & 0 & 0 & 0\\
          0 &  \lambda^{-1}_{2} & 0 & 0\\
          0 & 0 & \lambda^{-1}_{3} & 0 \\
          0 & 0 & 0 & \lambda^{-1}_{k} \\
     \end{array}
     \right]_{N \times M} \\\\
 \end{split}$$

## U, $\sum$ and $V^T$ matrices

In [54]:
print("U:\n {}".format(U))
print("E:\n {}".format(s))
print("VT:\n {}".format(VT))

U:
 [[-1. -0. -0.  0. -0.]
 [ 0. -1. -0.  0. -0.]
 [ 0.  0. -1.  0. -0.]
 [-0. -0. -0. -1. -0.]
 [-0. -0. -0. -0.  1.]]
E:
 [ 12.48101   9.50861   1.34556   0.        0.     ]
VT:
 [[-0.56226 -0.59286 -0.56226 -0.09013 -0.09013]
 [ 0.12664 -0.02877  0.12664 -0.69538 -0.69538]
 [ 0.40967 -0.80479  0.40967  0.09126  0.09126]
 [-0.70711  0.       0.70711 -0.       0.     ]
 [-0.      -0.       0.       0.70711 -0.70711]]


# We want the Z inverse matrix

$$Z^{-1}=V\sum^{-1}U^{T}$$

Actually, Z inverse is a pseudo-inverse or generalized inverse (penrose), because it is an aproximated solution, and we named Z inverse like:
    $$ Z^{+} = V \sum^{+} U^{T}$$


where $\sum^{+}$ is the matriz that contain the sigular values inverse non-zeros in this way: 

$$\begin{split}
     \mathbf{\sum^{+}} 
     & = \left[
     \begin{array}{ccc}
         E & 0 \\
          0 &  0
     \end{array}
     \right]_{N \times M} \\\\
 \end{split}$$

being E the $kxk$ matriz whose the element i-ésimo is $e_{ii}=e^{-1}_{i}$ for $1\le i\le k$

$$\begin{split}
     \mathbf{E} 
     & = \left[
     \begin{array}{ccc}
         \sigma_{1} & 0 & 0 & 0 & 0\\
          0 &  \sigma_{2} & 0 & 0 & 0\\
          0 & 0 & \sigma_{3} & 0 & 0\\
          0 & 0 & 0 & \sigma_{k} & 0 \\
          0 & 0 & 0 & 0 & 0
     \end{array}
     \right]_{N \times M} \\\\
 \end{split}$$

$\sigma=1/\lambda$

$$\sigma_{1} \gt \sigma_{2} \gt \sigma_{3} \dots \gt \sigma_{k}$$

# Resolvendo um sistema linear com SVD

## $$Ax=b$$

## $$x=A^{+}b$$

In [67]:
A = np.array([[10., 56., 15.],
              [30., 50., 0.],
              [70., 17., 0.]])

In [68]:
b= np.array([1.89, 1.76, 1.77])
len(b)


3

In [69]:
def inversa_sigular(s):
    m = len(s)

    E = [[0.0 for i in range(m)] for j in range(m)]
    for i in range(m):
        E[i][i] = 1.0 / s[i]   #!COLOCAR EM ORDEM DO MAIOR PARA O MENOR
    return E

In [87]:
(u, s, v) = np_svd(A)

ut=u.T
l=np.array([[0.11232396490585773, 0.0, 0.0],
 [0.0, 0.019057635920438732, 0.0],
 [0.0, 0.0, 0.010415883208889519]])

In [88]:
def solve(A, b):
    (u, s, v) = np_svd(A)
    #l = inversa_sigular(s)
    x1 = np.dot(v, l)
    x2 = np.dot(ut, b)
    x = np.dot(x1, x2)
    return x

In [89]:

x=solve(A, b)

In [90]:
x

array([ 0.24886, -0.24287,  0.02777])

In [86]:
y= np.linalg.solve(A,b) #Resolve diretamente. O resultado está batendo.

In [81]:
y

array([ 0.01959,  0.02344,  0.02541])